---
dependencies:
  - role: geerlingguy.mysql
    mysql_databases:
      - name: '{{ notes_dbname }}'
      - name: '{{ notes_search_dbname }}'
    mysql_users:
      - name: '{{ notes_dbuser }}'
        host: 127.0.0.1
        password: '{{ notes_dbpassword }}'
        priv: '{{ notes_dbname }}.*:ALL'
      - name: '{{ notes_search_dbuser }}'
        host: 127.0.0.1
        password: '{{ notes_search_dbpassword }}'
        priv: '{{ notes_search_dbname }}.*:ALL'

  - role: blocks/owner
    owner_name: '{{ notes_owner }}'
    owner_group: '{{ notes_owner }}'
    owner_ssh_keys: ['{{ lookup("file", "av_id_rsa.pub") }}']
    owner_envs: '{{ notes_env }}'

  - role: blocks/ssl-certificate
    cert_type: letsencrypt
    cert_name: '{{ notes_name }}'
    cert_email: anwinged@ya.ru
    cert_domains:
      - '{{ notes_domain }}'

  - role: blocks/php-app
    php_app_name: '{{ notes_name }}'
    php_app_user: '{{ notes_owner }}'
    php_app_group: '{{ notes_owner }}'
    php_app_directory: '{{ notes_dir }}'
    php_app_web_root: '{{ notes_web_root }}'
    php_app_nginx_config: nginx.conf.j2
    php_app_php_version: '7.1'
    php_app_fpm_listen: '{{ notes_php_connection }}'
    php_app_envs: '{{ notes_env }}'
