# https://taskfile.dev

version: '3'

vars:
  USER_ID:
    sh: id -u
  GROUP_ID:
    sh: id -g

tasks:
  edit-vars:
    cmds:
      - ansible-vault edit ansible/vars/vars.yml
    env:
      EDITOR: micro

  list-tags:
    cmds:
      - >-
        ansible-playbook
        --inventory="ansible/hosts_prod"
        --list-tags
        ansible/configuration.yml

  configure:
    internal: true
    vars:
      TAGS: '{{ (empty .TAGS) | ternary "" (list "--tags=\"" .TAGS "\"" | join "") }}'
    cmds:
      - >- 
        ansible-playbook
        --user="major"
        --become
        --inventory="ansible/hosts_prod"
        --extra-vars="ansible_python_interpreter=/usr/bin/python3"
        {{.TAGS}}
        -vvv
        ansible/configuration.yml

  configure-monitoring:
    cmds:
      - task: configure
        vars: { TAGS: 'monitoring' }

  configure-apps:
    cmds:
      - task: configure
        vars: { TAGS: 'webserver,apps,env' }

  configure-users:
    cmds:
      - task: configure
        vars: { TAGS: 'apps,env' }

  format-py-files:
    cmds:
      - >-
        docker run
        --rm
        -u {{.USER_ID}}:{{.GROUP_ID}}
        -v $PWD/app:/app
        -w /app
        pyfound/black:latest_release
        black .
