version: "3.2"
services:

  outline-app:
    image: outlinewiki/outline:0.76.2-0
    ports:
      - "${WEB_SERVER_PORT}:3000"
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: '${NODE_ENV}'
      SECRET_KEY: '${SECRET_KEY}'
      UTILS_SECRET: '${UTILS_SECRET}'
      DATABASE_URL: '${DATABASE_URL}'
      PGSSLMODE: '${PGSSLMODE}'
      REDIS_URL: '${REDIS_URL}'
      URL: '${URL}'
      FILE_STORAGE: '${FILE_STORAGE}'
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      AWS_REGION: '${AWS_REGION}'
      AWS_S3_ACCELERATE_URL: '${AWS_S3_ACCELERATE_URL}'
      AWS_S3_UPLOAD_BUCKET_URL: '${AWS_S3_UPLOAD_BUCKET_URL}'
      AWS_S3_UPLOAD_BUCKET_NAME: '${AWS_S3_UPLOAD_BUCKET_NAME}'
      AWS_S3_FORCE_PATH_STYLE: '${AWS_S3_FORCE_PATH_STYLE}'
      AWS_S3_ACL: '${AWS_S3_ACL}'
      OIDC_CLIENT_ID: '${OIDC_CLIENT_ID}'
      OIDC_CLIENT_SECRET: '${OIDC_CLIENT_SECRET}'
      OIDC_AUTH_URI: '${OIDC_AUTH_URI}'
      OIDC_TOKEN_URI: '${OIDC_TOKEN_URI}'
      OIDC_USERINFO_URI: '${OIDC_USERINFO_URI}'
      OIDC_LOGOUT_URI: '${OIDC_LOGOUT_URI}'
      OIDC_USERNAME_CLAIM: '${OIDC_USERNAME_CLAIM}'
      OIDC_DISPLAY_NAME: '${OIDC_DISPLAY_NAME}'

  redis:
    image: redis:7.2-bookworm
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]

  postgres:
    image: postgres:16.3-bookworm
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'

volumes:
  database-data:
