version: "3"

# Images: https://quay.io/repository/keycloak/keycloak?tab=tags&tag=latest
# Configuration: https://www.keycloak.org/server/all-config

# NB
# - На проде были проблемы с правами к директории data, пришлось выдать 777
# - Переменную KC_HOSTNAME_ADMIN_URL нужно указать вместе с KC_HOSTNAME_URL, иначе будут ошибки 403

services:

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command: ["start-dev"]
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
      KC_HOSTNAME_URL: "https://kk.vakhrushev.me"
      KC_HOSTNAME_ADMIN_URL: "https://kk.vakhrushev.me"
    ports:
      - "${WEB_SERVER_PORT}:8080"
    volumes:
      - "./data:/opt/keycloak/data"
