version: "3"

# Images: https://quay.io/repository/keycloak/keycloak?tab=tags&tag=latest
# Configuration: https://www.keycloak.org/server/all-config

services:

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command: ["start-dev"]
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
    ports:
      - "${WEB_SERVER_PORT}:8080"
    volumes:
      - "./data:/opt/keycloak/data"
