version: "3"

services:

  server:
    image: gitea/gitea:1.21.11
    environment:
      - "USER_UID=${USER_UID}"
      - "USER_GID=${USER_GID}"
      - "GITEA__server__SSH_PORT=2222"
    restart: unless-stopped
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${WEB_SERVER_PORT}:3000"
      - "2222:22"
