---
- name: "Create nginx config for {{ nginx_proxy_name }} from {{ nginx_proxy_template }}."
  template:
    src: '{{ nginx_proxy_template }}'
    dest: "/etc/nginx/sites-enabled/{{ nginx_proxy_name }}.conf"
  notify: restart nginx
  tags:
    - webserver

- name: "Create root folder for {{ nginx_proxy_name }}."
  file:
    path: "{{ nginx_proxy_dir }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: www-data
    recurse: yes
  notify: restart nginx
  tags:
    - webserver
