---
- name: 'Create owner.'
  import_role:
    name: owner
  vars:
    owner_name: '{{ username }}'
    owner_group: '{{ username }}'
    owner_extra_groups: '{{ extra_groups | default([]) }}'
    owner_ssh_keys: '{{ ssh_keys | default([]) }}'
    owner_env: '{{ env | default({}) }}'

- name: 'Create web dir.'
  file:
    path: '/var/www/{{ username }}'
    state: directory
    owner: '{{ username }}'
    group: '{{ username }}'
    recurse: True

- name: 'Login to yandex docker registry.'
  ansible.builtin.script:
    cmd: 'files/yandex-docker-registry-auth.sh'
  become: yes
  become_user: '{{ username }}'
