---
- name: Create owner.
  include_role:
    name: owner
  vars:
    owner_name: '{{ username }}'
    owner_group: '{{ username }}'
    owner_ssh_keys: '{{ ssh_keys | default([]) }}'
    owner_envs: '{{ env | default({}) }}'
