---
- name: 'Check app requirements for {{ owner_name }}.'
  fail:
    msg: You must set owner name.
  when: not owner_name

- name: 'Create group "{{ owner_group }}".'
  group:
    name: '{{ owner_group }}'
    state: present

- name: 'Create user "{{ owner_name }}".'
  user:
    name: '{{ owner_name }}'
    group: '{{ owner_group }}'
    shell: /bin/bash

- name: 'Set up user ssh keys for {{ owner_name }}.'
  authorized_key:
    user: '{{ owner_name }}'
    key: '{{ item }}'
    state: present
  with_items: '{{ owner_ssh_keys }}'

- name: 'Set up environment variables for {{ owner_name }}.'
  template:
    src: envs.j2
    dest: '/home/{{ owner_name }}/.envs'

- name: 'Remove environment variables for {{ owner_name }} from bashrc.'
  lineinfile:
    path: '/home/{{ owner_name }}/.bashrc'
    regexp: '^export {{ item.key }}='
    state: absent
  with_dict: '{{ owner_envs }}'

- name: 'Include environment variables for {{ owner_name }} in bashrc.'
  lineinfile:
    path: '/home/{{ owner_name }}/.bashrc'
    regexp: '^\. ~\/\.envs'
    line: '. ~/.envs'
