---
- hosts: all
  become: true

  vars:
    deploy_user: deployer

    timezone: UTC

    # nginx settings

    nginx_remove_default_vhost: true

    # php settings

    php_version: '7.1'
    php_packages_extra:
      - 'php{{ php_version }}'
      - 'php{{ php_version }}-curl'
      - 'php{{ php_version }}-gd'
      - 'php{{ php_version }}-fpm'
      - 'php{{ php_version }}-mbstring'
      - 'php{{ php_version }}-xml'
      - 'php{{ php_version }}-intl'
      - 'php{{ php_version }}-zip'
      - 'php{{ php_version }}-mysql'
    php_webserver_daemon: nginx
    php_enable_php_fpm: true
    php_date_timezone: '{{ timezone }}'

  pre_tasks:
    - name: Ensure that PHP PPA is added.
      apt_repository: repo=ppa:ondrej/php state=present
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=86400
    - name: Install system packages
      apt: pkg={{ item }} state=latest
      with_items:
        - curl
        - git
        - make
        - python-software-properties
        - wget
        - zip
    - name: Add deploy user
      user:
        name: '{{ deploy_user }}'
        groups: www-data

  roles:
    - yatesr.timezone
    - geerlingguy.nginx
    - geerlingguy.php-versions
    - geerlingguy.php

    - homepage
    - s2photo
    - notes
