---
- hosts: all
  become: true

  vars:
    timezone: UTC
    nginx_remove_default_vhost: true

  roles:
    - yatesr.timezone
    - geerlingguy.nginx
    - server
    - site-anwinged
    - site-s2photo
