---
- hosts: all
  become: true

  vars:
    timezone: UTC
    nginx_remove_default_vhost: true

  roles:
    - yatesr.timezone
    - geerlingguy.nginx
    - server
    - role: static-site
      static_site_name: anwinged
      static_site_domain: anwinged.ru
    - role: static-site
      static_site_name: s2photo
      static_site_domain: s2photo.ru
