---
- src: yatesr.timezone
  version: 1.0.0

- src: geerlingguy.nginx
  version: 2.5.0

- src: geerlingguy.php-versions
  version: 1.1.0

- src: geerlingguy.php
  version: 3.4.5

- src: geerlingguy.mysql
  version: 2.8.0
