---
- name: Ensure certificate storage exists.
  file:
    path: '{{ cert_directory }}'
    state: directory

- include: self-signed.yml
  when: cert_type == 'self-signed'

- include: letsencrypt.yml
  when: cert_type == 'letsencrypt'

- name: Generate dhparams.
  shell: 'openssl dhparam -out {{ cert_dhparam }} {{ cert_dhparam_n }}'
  args:
    creates: '{{ cert_dhparam }}'

- name: Set facts about generated files.
  set_fact:
    '{{ cert_name }}_ssl_key': '{{ cert_key }}'
    '{{ cert_name }}_ssl_certificate': '{{ cert_certificate }}'
    '{{ cert_name }}_ssl_dhparam': '{{ cert_dhparam }}'
